name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t my-backend:latest ./backend
          docker tag my-backend:latest your-dockerhub-username/my-backend:latest
          docker push your-dockerhub-username/my-backend:latest

      - name: Deploy to EC2 (Blue-Green)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            if docker ps --filter "name=backend-blue" | grep backend-blue; then
                ACTIVE=blue
                INACTIVE=green
                PORT=8082
            else
                ACTIVE=green
                INACTIVE=blue
                PORT=8081
            fi

            docker pull your-dockerhub-username/my-backend:latest
            docker stop backend-$INACTIVE || true
            docker rm backend-$INACTIVE || true
            docker run -d --name backend-$INACTIVE -p $PORT:8080 your-dockerhub-username/my-backend:latest

            # Nginx upstream 교체 후 reload
            sed -i "s/server 127.0.0.1:808[12];/server 127.0.0.1:$PORT;/g" /etc/nginx/conf.d/backend.conf
            nginx -s reload

            echo "Deployment complete. Active container: $INACTIVE"